// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPipecatApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPipecatApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPipecatApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPipecatApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPipecatApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPipecatApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum ConnectionState: Int {
  case connecting = 0
  case connected = 1
  case disconnected = 2
}

enum SpeakingState: Int {
  /// Emitted when the user begins speaking
  case userStartedSpeaking = 0
  /// Emitted when the user stops speaking
  case userStoppedSpeaking = 1
  /// Emitted when the bot begins speaking
  case botStartedSpeaking = 2
  /// Emitted when the bot stops speaking
  case botStoppedSpeaking = 3
}

enum UserMuteState: Int {
  case started = 0
  case stopped = 1
}

enum InsightType: Int {
  case botLlmStarted = 0
  case botLlmStopped = 1
  case botTtsStarted = 2
  case botTtsStopped = 3
}

enum BotConnectionState: Int {
  case connected = 0
  case disconnected = 1
}

/// Parameters for starting the bot and connecting
///
/// Used to connect to your transport (for example: a Daily room)
///
/// Generated class from Pigeon that represents data sent in messages.
struct StartBotParams: Hashable {
  /// API endpoint to connect to
  var url: String
  /// Optional auth token
  ///
  /// The package does not prepend "Bearer " to your token, ensure that
  /// it has the proper value first before adding it.
  var token: String? = nil
  /// Should enable microphone when starting a call
  var shouldEnableMicrophone: Bool
  /// Should enable camera when starting a call
  var shouldEnableCamera: Bool
  /// Additional headers
  var headers: [String: String]? = nil
  /// Defaults to `/connect`
  var connectPath: String
  /// Defaults to 30000 natively
  var timeoutInMilliseconds: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StartBotParams? {
    let url = pigeonVar_list[0] as! String
    let token: String? = nilOrValue(pigeonVar_list[1])
    let shouldEnableMicrophone = pigeonVar_list[2] as! Bool
    let shouldEnableCamera = pigeonVar_list[3] as! Bool
    let headers: [String: String]? = nilOrValue(pigeonVar_list[4])
    let connectPath = pigeonVar_list[5] as! String
    let timeoutInMilliseconds: Int64? = nilOrValue(pigeonVar_list[6])

    return StartBotParams(
      url: url,
      token: token,
      shouldEnableMicrophone: shouldEnableMicrophone,
      shouldEnableCamera: shouldEnableCamera,
      headers: headers,
      connectPath: connectPath,
      timeoutInMilliseconds: timeoutInMilliseconds
    )
  }
  func toList() -> [Any?] {
    return [
      url,
      token,
      shouldEnableMicrophone,
      shouldEnableCamera,
      headers,
      connectPath,
      timeoutInMilliseconds,
    ]
  }
  static func == (lhs: StartBotParams, rhs: StartBotParams) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Parameters for sending text input to the bot.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SendTextParams: Hashable {
  /// Text content to send.
  var content: String
  /// Whether the bot should run this input immediately.
  var runImmediately: Bool? = nil
  /// Whether the bot should respond with audio.
  var audioResponse: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SendTextParams? {
    let content = pigeonVar_list[0] as! String
    let runImmediately: Bool? = nilOrValue(pigeonVar_list[1])
    let audioResponse: Bool? = nilOrValue(pigeonVar_list[2])

    return SendTextParams(
      content: content,
      runImmediately: runImmediately,
      audioResponse: audioResponse
    )
  }
  func toList() -> [Any?] {
    return [
      content,
      runImmediately,
      audioResponse,
    ]
  }
  static func == (lhs: SendTextParams, rhs: SendTextParams) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Parameters for sending LLM function call result using RTVI standard message.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SendLlmFunctionCallResultParams: Hashable {
  /// Function name from the original LLM function call.
  var functionName: String
  /// Tool call identifier from the original LLM function call.
  var toolCallId: String
  /// JSON-serialized arguments from the original function call.
  var argumentsJson: String
  /// JSON-serialized function result payload.
  var resultJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SendLlmFunctionCallResultParams? {
    let functionName = pigeonVar_list[0] as! String
    let toolCallId = pigeonVar_list[1] as! String
    let argumentsJson = pigeonVar_list[2] as! String
    let resultJson = pigeonVar_list[3] as! String

    return SendLlmFunctionCallResultParams(
      functionName: functionName,
      toolCallId: toolCallId,
      argumentsJson: argumentsJson,
      resultJson: resultJson
    )
  }
  func toList() -> [Any?] {
    return [
      functionName,
      toolCallId,
      argumentsJson,
      resultJson,
    ]
  }
  static func == (lhs: SendLlmFunctionCallResultParams, rhs: SendLlmFunctionCallResultParams) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Parameters for sending a custom RTVI client-message payload.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SendClientMessageParams: Hashable {
  /// Custom client message type.
  var msgType: String
  /// JSON-serialized payload for the custom message.
  var dataJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SendClientMessageParams? {
    let msgType = pigeonVar_list[0] as! String
    let dataJson = pigeonVar_list[1] as! String

    return SendClientMessageParams(
      msgType: msgType,
      dataJson: dataJson
    )
  }
  func toList() -> [Any?] {
    return [
      msgType,
      dataJson,
    ]
  }
  static func == (lhs: SendClientMessageParams, rhs: SendClientMessageParams) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Parameters for sending a request-style RTVI client-message payload.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SendClientRequestParams: Hashable {
  /// Custom client request message type.
  var msgType: String
  /// JSON-serialized payload for the request.
  var dataJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SendClientRequestParams? {
    let msgType = pigeonVar_list[0] as! String
    let dataJson = pigeonVar_list[1] as! String

    return SendClientRequestParams(
      msgType: msgType,
      dataJson: dataJson
    )
  }
  func toList() -> [Any?] {
    return [
      msgType,
      dataJson,
    ]
  }
  static func == (lhs: SendClientRequestParams, rhs: SendClientRequestParams) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Result payload returned by server-response for a client request.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SendClientRequestResult: Hashable {
  /// Message type echoed from server response `data.t`.
  var msgType: String
  /// JSON-serialized response payload from server response `data.d`.
  var dataJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SendClientRequestResult? {
    let msgType = pigeonVar_list[0] as! String
    let dataJson = pigeonVar_list[1] as! String

    return SendClientRequestResult(
      msgType: msgType,
      dataJson: dataJson
    )
  }
  func toList() -> [Any?] {
    return [
      msgType,
      dataJson,
    ]
  }
  static func == (lhs: SendClientRequestResult, rhs: SendClientRequestResult) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Events that the client receives on a session.
///
/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol PipecatEvent {

}

/// Emitted when there's a change in the connection state.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ConnectionStateEvent: PipecatEvent {
  var state: ConnectionState


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConnectionStateEvent? {
    let state = pigeonVar_list[0] as! ConnectionState

    return ConnectionStateEvent(
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      state
    ]
  }
  static func == (lhs: ConnectionStateEvent, rhs: ConnectionStateEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Emitted when there's a problem connecting or during
/// the call session.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BackendErrorEvent: PipecatEvent {
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BackendErrorEvent? {
    let message = pigeonVar_list[0] as! String

    return BackendErrorEvent(
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      message
    ]
  }
  static func == (lhs: BackendErrorEvent, rhs: BackendErrorEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Real-time transcription of user speech,
/// including both partial and final results.
///
/// Generated class from Pigeon that represents data sent in messages.
struct UserTranscriptionEvent: PipecatEvent {
  var text: String
  var isFinal: Bool
  var timestamp: String
  var userId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UserTranscriptionEvent? {
    let text = pigeonVar_list[0] as! String
    let isFinal = pigeonVar_list[1] as! Bool
    let timestamp = pigeonVar_list[2] as! String
    let userId = pigeonVar_list[3] as! String

    return UserTranscriptionEvent(
      text: text,
      isFinal: isFinal,
      timestamp: timestamp,
      userId: userId
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      isFinal,
      timestamp,
      userId,
    ]
  }
  static func == (lhs: UserTranscriptionEvent, rhs: UserTranscriptionEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// The best-effort representation of the bot's output text, including both
/// spoken and unspoken text.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BotOutputEvent: PipecatEvent {
  /// The output text from the bot.
  var text: String
  /// Indicates if this text was spoken by the bot.
  var isSpoken: Bool
  /// Indicates how the text was aggregated.
  var aggregatedBy: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BotOutputEvent? {
    let text = pigeonVar_list[0] as! String
    let isSpoken = pigeonVar_list[1] as! Bool
    let aggregatedBy = pigeonVar_list[2] as! String

    return BotOutputEvent(
      text: text,
      isSpoken: isSpoken,
      aggregatedBy: aggregatedBy
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      isSpoken,
      aggregatedBy,
    ]
  }
  static func == (lhs: BotOutputEvent, rhs: BotOutputEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SpeakingEvent: PipecatEvent {
  var state: SpeakingState


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SpeakingEvent? {
    let state = pigeonVar_list[0] as! SpeakingState

    return SpeakingEvent(
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      state
    ]
  }
  static func == (lhs: SpeakingEvent, rhs: SpeakingEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UserMuteEvent: PipecatEvent {
  var state: UserMuteState


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UserMuteEvent? {
    let state = pigeonVar_list[0] as! UserMuteState

    return UserMuteEvent(
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      state
    ]
  }
  static func == (lhs: UserMuteEvent, rhs: UserMuteEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ServerInsightEvent: PipecatEvent {
  var type: InsightType


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ServerInsightEvent? {
    let type = pigeonVar_list[0] as! InsightType

    return ServerInsightEvent(
      type: type
    )
  }
  func toList() -> [Any?] {
    return [
      type
    ]
  }
  static func == (lhs: ServerInsightEvent, rhs: ServerInsightEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Aggregated user input text that is sent to the LLM.
///
/// Generated class from Pigeon that represents data sent in messages.
struct UserLLMText: PipecatEvent {
  var text: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UserLLMText? {
    let text = pigeonVar_list[0] as! String

    return UserLLMText(
      text: text
    )
  }
  func toList() -> [Any?] {
    return [
      text
    ]
  }
  static func == (lhs: UserLLMText, rhs: UserLLMText) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Individual tokens streamed from the LLM as they are generated.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BotLLMText: PipecatEvent {
  var text: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BotLLMText? {
    let text = pigeonVar_list[0] as! String

    return BotLLMText(
      text: text
    )
  }
  func toList() -> [Any?] {
    return [
      text
    ]
  }
  static func == (lhs: BotLLMText, rhs: BotLLMText) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// The per-token text output of the text-to-speech (TTS) service
/// (what the TTS actually says).
///
/// Generated class from Pigeon that represents data sent in messages.
struct BotTTSText: PipecatEvent {
  var text: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BotTTSText? {
    let text = pigeonVar_list[0] as! String

    return BotTTSText(
      text: text
    )
  }
  func toList() -> [Any?] {
    return [
      text
    ]
  }
  static func == (lhs: BotTTSText, rhs: BotTTSText) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Emitted when the LLM has decided to call a function (no args yet).
///
/// Corresponds to the modern pipecat RTVI message `llm-function-call-started`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct LlmFunctionCallStartedEvent: PipecatEvent {
  /// May be omitted by the server based on its function-call report level.
  var functionName: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LlmFunctionCallStartedEvent? {
    let functionName: String? = nilOrValue(pigeonVar_list[0])

    return LlmFunctionCallStartedEvent(
      functionName: functionName
    )
  }
  func toList() -> [Any?] {
    return [
      functionName
    ]
  }
  static func == (lhs: LlmFunctionCallStartedEvent, rhs: LlmFunctionCallStartedEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Emitted when the LLM function call is in flight with full call data.
///
/// Corresponds to the modern pipecat RTVI message
/// `llm-function-call-in-progress`. This is the event new app code should
/// listen to in order to actually execute the tool.
///
/// Generated class from Pigeon that represents data sent in messages.
struct LlmFunctionCallInProgressEvent: PipecatEvent {
  var toolCallId: String
  /// May be omitted by the server based on its function-call report level.
  var functionName: String? = nil
  /// Deterministically-serialized JSON arguments payload, or null if the
  /// server omitted arguments based on its report level.
  var argumentsJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LlmFunctionCallInProgressEvent? {
    let toolCallId = pigeonVar_list[0] as! String
    let functionName: String? = nilOrValue(pigeonVar_list[1])
    let argumentsJson: String? = nilOrValue(pigeonVar_list[2])

    return LlmFunctionCallInProgressEvent(
      toolCallId: toolCallId,
      functionName: functionName,
      argumentsJson: argumentsJson
    )
  }
  func toList() -> [Any?] {
    return [
      toolCallId,
      functionName,
      argumentsJson,
    ]
  }
  static func == (lhs: LlmFunctionCallInProgressEvent, rhs: LlmFunctionCallInProgressEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Emitted when the LLM function call has finished or been cancelled.
///
/// Corresponds to the modern pipecat RTVI message `llm-function-call-stopped`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct LlmFunctionCallStoppedEvent: PipecatEvent {
  var toolCallId: String
  var cancelled: Bool
  /// May be omitted by the server based on its function-call report level.
  var functionName: String? = nil
  /// Deterministically-serialized JSON result payload, or null if the call was
  /// cancelled or the server omitted the result based on its report level.
  var resultJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LlmFunctionCallStoppedEvent? {
    let toolCallId = pigeonVar_list[0] as! String
    let cancelled = pigeonVar_list[1] as! Bool
    let functionName: String? = nilOrValue(pigeonVar_list[2])
    let resultJson: String? = nilOrValue(pigeonVar_list[3])

    return LlmFunctionCallStoppedEvent(
      toolCallId: toolCallId,
      cancelled: cancelled,
      functionName: functionName,
      resultJson: resultJson
    )
  }
  func toList() -> [Any?] {
    return [
      toolCallId,
      cancelled,
      functionName,
      resultJson,
    ]
  }
  static func == (lhs: LlmFunctionCallStoppedEvent, rhs: LlmFunctionCallStoppedEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct InputStatusUpdatedEvent: PipecatEvent {
  var isCurrentMicrophoneEnabled: Bool
  var isCurrentCameraEnabled: Bool
  var isBotAudioMuted: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InputStatusUpdatedEvent? {
    let isCurrentMicrophoneEnabled = pigeonVar_list[0] as! Bool
    let isCurrentCameraEnabled = pigeonVar_list[1] as! Bool
    let isBotAudioMuted = pigeonVar_list[2] as! Bool

    return InputStatusUpdatedEvent(
      isCurrentMicrophoneEnabled: isCurrentMicrophoneEnabled,
      isCurrentCameraEnabled: isCurrentCameraEnabled,
      isBotAudioMuted: isBotAudioMuted
    )
  }
  func toList() -> [Any?] {
    return [
      isCurrentMicrophoneEnabled,
      isCurrentCameraEnabled,
      isBotAudioMuted,
    ]
  }
  static func == (lhs: InputStatusUpdatedEvent, rhs: InputStatusUpdatedEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BotConnectionEvent: PipecatEvent {
  var state: BotConnectionState
  var participantId: String
  var participantName: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BotConnectionEvent? {
    let state = pigeonVar_list[0] as! BotConnectionState
    let participantId = pigeonVar_list[1] as! String
    let participantName: String? = nilOrValue(pigeonVar_list[2])

    return BotConnectionEvent(
      state: state,
      participantId: participantId,
      participantName: participantName
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      participantId,
      participantName,
    ]
  }
  static func == (lhs: BotConnectionEvent, rhs: BotConnectionEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BotReadyEvent: PipecatEvent {
  var version: String
  var aboutJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BotReadyEvent? {
    let version = pigeonVar_list[0] as! String
    let aboutJson: String? = nilOrValue(pigeonVar_list[1])

    return BotReadyEvent(
      version: version,
      aboutJson: aboutJson
    )
  }
  func toList() -> [Any?] {
    return [
      version,
      aboutJson,
    ]
  }
  static func == (lhs: BotReadyEvent, rhs: BotReadyEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ServerMessageEvent: PipecatEvent {
  /// Deterministically-serialized JSON payload from RTVI server-message data.
  var rawJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ServerMessageEvent? {
    let rawJson = pigeonVar_list[0] as! String

    return ServerMessageEvent(
      rawJson: rawJson
    )
  }
  func toList() -> [Any?] {
    return [
      rawJson
    ]
  }
  static func == (lhs: ServerMessageEvent, rhs: ServerMessageEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PipecatMetricSample: Hashable {
  var processor: String
  var value: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PipecatMetricSample? {
    let processor = pigeonVar_list[0] as! String
    let value = pigeonVar_list[1] as! Double

    return PipecatMetricSample(
      processor: processor,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      processor,
      value,
    ]
  }
  static func == (lhs: PipecatMetricSample, rhs: PipecatMetricSample) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MetricsEvent: PipecatEvent {
  var processing: [PipecatMetricSample]? = nil
  var ttfb: [PipecatMetricSample]? = nil
  /// Deterministically-serialized full metrics payload.
  var rawJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MetricsEvent? {
    let processing: [PipecatMetricSample]? = nilOrValue(pigeonVar_list[0])
    let ttfb: [PipecatMetricSample]? = nilOrValue(pigeonVar_list[1])
    let rawJson: String? = nilOrValue(pigeonVar_list[2])

    return MetricsEvent(
      processing: processing,
      ttfb: ttfb,
      rawJson: rawJson
    )
  }
  func toList() -> [Any?] {
    return [
      processing,
      ttfb,
      rawJson,
    ]
  }
  static func == (lhs: MetricsEvent, rhs: MetricsEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TimelineEvent: Hashable {
  var sequence: Int64
  var sessionEpoch: Int64
  var emittedAtMs: Int64
  var event: PipecatEvent


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TimelineEvent? {
    let sequence = pigeonVar_list[0] as! Int64
    let sessionEpoch = pigeonVar_list[1] as! Int64
    let emittedAtMs = pigeonVar_list[2] as! Int64
    let event = pigeonVar_list[3] as! PipecatEvent

    return TimelineEvent(
      sequence: sequence,
      sessionEpoch: sessionEpoch,
      emittedAtMs: emittedAtMs,
      event: event
    )
  }
  func toList() -> [Any?] {
    return [
      sequence,
      sessionEpoch,
      emittedAtMs,
      event,
    ]
  }
  static func == (lhs: TimelineEvent, rhs: TimelineEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Audio level data for visualizers.
/// Sent at high frequency (~50-100ms intervals).
///
/// Generated class from Pigeon that represents data sent in messages.
struct AudioLevel: Hashable {
  /// Normalized audio level from 0.0 (silent) to 1.0 (loud)
  var level: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AudioLevel? {
    let level = pigeonVar_list[0] as! Double

    return AudioLevel(
      level: level
    )
  }
  func toList() -> [Any?] {
    return [
      level
    ]
  }
  static func == (lhs: AudioLevel, rhs: AudioLevel) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

private class PipecatApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ConnectionState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SpeakingState(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return UserMuteState(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return InsightType(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BotConnectionState(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      return StartBotParams.fromList(self.readValue() as! [Any?])
    case 135:
      return SendTextParams.fromList(self.readValue() as! [Any?])
    case 136:
      return SendLlmFunctionCallResultParams.fromList(self.readValue() as! [Any?])
    case 137:
      return SendClientMessageParams.fromList(self.readValue() as! [Any?])
    case 138:
      return SendClientRequestParams.fromList(self.readValue() as! [Any?])
    case 139:
      return SendClientRequestResult.fromList(self.readValue() as! [Any?])
    case 140:
      return ConnectionStateEvent.fromList(self.readValue() as! [Any?])
    case 141:
      return BackendErrorEvent.fromList(self.readValue() as! [Any?])
    case 142:
      return UserTranscriptionEvent.fromList(self.readValue() as! [Any?])
    case 143:
      return BotOutputEvent.fromList(self.readValue() as! [Any?])
    case 144:
      return SpeakingEvent.fromList(self.readValue() as! [Any?])
    case 145:
      return UserMuteEvent.fromList(self.readValue() as! [Any?])
    case 146:
      return ServerInsightEvent.fromList(self.readValue() as! [Any?])
    case 147:
      return UserLLMText.fromList(self.readValue() as! [Any?])
    case 148:
      return BotLLMText.fromList(self.readValue() as! [Any?])
    case 149:
      return BotTTSText.fromList(self.readValue() as! [Any?])
    case 150:
      return LlmFunctionCallStartedEvent.fromList(self.readValue() as! [Any?])
    case 151:
      return LlmFunctionCallInProgressEvent.fromList(self.readValue() as! [Any?])
    case 152:
      return LlmFunctionCallStoppedEvent.fromList(self.readValue() as! [Any?])
    case 153:
      return InputStatusUpdatedEvent.fromList(self.readValue() as! [Any?])
    case 154:
      return BotConnectionEvent.fromList(self.readValue() as! [Any?])
    case 155:
      return BotReadyEvent.fromList(self.readValue() as! [Any?])
    case 156:
      return ServerMessageEvent.fromList(self.readValue() as! [Any?])
    case 157:
      return PipecatMetricSample.fromList(self.readValue() as! [Any?])
    case 158:
      return MetricsEvent.fromList(self.readValue() as! [Any?])
    case 159:
      return TimelineEvent.fromList(self.readValue() as! [Any?])
    case 160:
      return AudioLevel.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PipecatApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ConnectionState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? SpeakingState {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? UserMuteState {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? InsightType {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? BotConnectionState {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? StartBotParams {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? SendTextParams {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? SendLlmFunctionCallResultParams {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? SendClientMessageParams {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? SendClientRequestParams {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? SendClientRequestResult {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? ConnectionStateEvent {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? BackendErrorEvent {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? UserTranscriptionEvent {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? BotOutputEvent {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? SpeakingEvent {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? UserMuteEvent {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? ServerInsightEvent {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? UserLLMText {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? BotLLMText {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? BotTTSText {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? LlmFunctionCallStartedEvent {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? LlmFunctionCallInProgressEvent {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? LlmFunctionCallStoppedEvent {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else if let value = value as? InputStatusUpdatedEvent {
      super.writeByte(153)
      super.writeValue(value.toList())
    } else if let value = value as? BotConnectionEvent {
      super.writeByte(154)
      super.writeValue(value.toList())
    } else if let value = value as? BotReadyEvent {
      super.writeByte(155)
      super.writeValue(value.toList())
    } else if let value = value as? ServerMessageEvent {
      super.writeByte(156)
      super.writeValue(value.toList())
    } else if let value = value as? PipecatMetricSample {
      super.writeByte(157)
      super.writeValue(value.toList())
    } else if let value = value as? MetricsEvent {
      super.writeByte(158)
      super.writeValue(value.toList())
    } else if let value = value as? TimelineEvent {
      super.writeByte(159)
      super.writeValue(value.toList())
    } else if let value = value as? AudioLevel {
      super.writeByte(160)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PipecatApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PipecatApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PipecatApiPigeonCodecWriter(data: data)
  }
}

class PipecatApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PipecatApiPigeonCodec(readerWriter: PipecatApiPigeonCodecReaderWriter())
}

var pipecatApiPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: PipecatApiPigeonCodecReaderWriter());


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PipecatHostApi {
  /// Starts the session and connects to your transport
  func startAndConnect(parameters: StartBotParams, completion: @escaping (Result<Void, Error>) -> Void)
  /// Acts as a dispose too
  func disconnect(completion: @escaping (Result<Void, Error>) -> Void)
  /// Toggle local microphone input capture and outbound publishing.
  func toggleMicrophone(isEnabled: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  /// Toggle your camera
  func toggleCamera(isEnabled: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  /// Toggle bot audio by changing the local remote-audio subscription.
  func muteBotAudio(isMuted: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  /// Send typed text input to the bot.
  func sendText(parameters: SendTextParams, completion: @escaping (Result<Void, Error>) -> Void)
  /// Send LLM function call result to the bot following RTVI message schema.
  func sendLlmFunctionCallResult(parameters: SendLlmFunctionCallResultParams, completion: @escaping (Result<Void, Error>) -> Void)
  /// Send a custom RTVI client-message payload to the bot.
  func sendClientMessage(parameters: SendClientMessageParams, completion: @escaping (Result<Void, Error>) -> Void)
  /// Send a custom RTVI client-message request and await server-response.
  func sendClientRequest(parameters: SendClientRequestParams, completion: @escaping (Result<SendClientRequestResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PipecatHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PipecatApiPigeonCodec.shared }
  /// Sets up an instance of `PipecatHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PipecatHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Starts the session and connects to your transport
    let startAndConnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.startAndConnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startAndConnectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let parametersArg = args[0] as! StartBotParams
        api.startAndConnect(parameters: parametersArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startAndConnectChannel.setMessageHandler(nil)
    }
    /// Acts as a dispose too
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { _, reply in
        api.disconnect { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    /// Toggle local microphone input capture and outbound publishing.
    let toggleMicrophoneChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.toggleMicrophone\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      toggleMicrophoneChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isEnabledArg = args[0] as! Bool
        api.toggleMicrophone(isEnabled: isEnabledArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      toggleMicrophoneChannel.setMessageHandler(nil)
    }
    /// Toggle your camera
    let toggleCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.toggleCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      toggleCameraChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isEnabledArg = args[0] as! Bool
        api.toggleCamera(isEnabled: isEnabledArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      toggleCameraChannel.setMessageHandler(nil)
    }
    /// Toggle bot audio by changing the local remote-audio subscription.
    let muteBotAudioChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.muteBotAudio\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      muteBotAudioChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isMutedArg = args[0] as! Bool
        api.muteBotAudio(isMuted: isMutedArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      muteBotAudioChannel.setMessageHandler(nil)
    }
    /// Send typed text input to the bot.
    let sendTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.sendText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let parametersArg = args[0] as! SendTextParams
        api.sendText(parameters: parametersArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendTextChannel.setMessageHandler(nil)
    }
    /// Send LLM function call result to the bot following RTVI message schema.
    let sendLlmFunctionCallResultChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.sendLlmFunctionCallResult\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendLlmFunctionCallResultChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let parametersArg = args[0] as! SendLlmFunctionCallResultParams
        api.sendLlmFunctionCallResult(parameters: parametersArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendLlmFunctionCallResultChannel.setMessageHandler(nil)
    }
    /// Send a custom RTVI client-message payload to the bot.
    let sendClientMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.sendClientMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendClientMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let parametersArg = args[0] as! SendClientMessageParams
        api.sendClientMessage(parameters: parametersArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendClientMessageChannel.setMessageHandler(nil)
    }
    /// Send a custom RTVI client-message request and await server-response.
    let sendClientRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.sendClientRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendClientRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let parametersArg = args[0] as! SendClientRequestParams
        api.sendClientRequest(parameters: parametersArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendClientRequestChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class TimelineEventsStreamHandler: PigeonEventChannelWrapper<TimelineEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: TimelineEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatEventStreamApi.timelineEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<TimelineEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: pipecatApiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class LocalAudioLevelStreamHandler: PigeonEventChannelWrapper<AudioLevel> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: LocalAudioLevelStreamHandler) {
    var channelName = "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatEventStreamApi.localAudioLevel"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<AudioLevel>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: pipecatApiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class RemoteAudioLevelStreamHandler: PigeonEventChannelWrapper<AudioLevel> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: RemoteAudioLevelStreamHandler) {
    var channelName = "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatEventStreamApi.remoteAudioLevel"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<AudioLevel>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: pipecatApiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
