// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  @preconcurrency import Flutter
#elseif os(macOS)
  @preconcurrency import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPipecatApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPipecatApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPipecatApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPipecatApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPipecatApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPipecatApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum ConnectionState: Int {
  case connecting = 0
  case connected = 1
  case disconnected = 2
}

enum SpeakingState: Int {
  /// Emitted when the user begins speaking
  case userStartedSpeaking = 0
  /// Emitted when the user stops speaking
  case userStoppedSpeaking = 1
  /// Emitted when the bot begins speaking
  case botStartedSpeaking = 2
  /// Emitted when the bot stops speaking
  case botStoppedSpeaking = 3
}

enum InsightType: Int {
  case botLlmStarted = 0
  case botLlmStopped = 1
  case botTtsStarted = 2
  case botTtsStopped = 3
}

/// Parameters for starting the bot and connecting
///
/// Used to connect to your transport (for example: a Daily room)
///
/// Generated class from Pigeon that represents data sent in messages.
struct StartBotParams: Hashable {
  /// API endpoint to connect to
  var url: String
  /// Optional auth token
  ///
  /// The package does not prepend "Bearer " to your token, ensure that
  /// it has the proper value first before adding it.
  var token: String? = nil
  /// Should enable microphone when starting a call
  var shouldEnableMicrophone: Bool
  /// Should enable camera when starting a call
  var shouldEnableCamera: Bool
  /// Additional headers
  var headers: [String: String]? = nil
  /// Defaults to `/connect`
  var connectPath: String
  /// Defaults to 30000 natively
  var timeoutInMilliseconds: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StartBotParams? {
    let url = pigeonVar_list[0] as! String
    let token: String? = nilOrValue(pigeonVar_list[1])
    let shouldEnableMicrophone = pigeonVar_list[2] as! Bool
    let shouldEnableCamera = pigeonVar_list[3] as! Bool
    let headers: [String: String]? = nilOrValue(pigeonVar_list[4])
    let connectPath = pigeonVar_list[5] as! String
    let timeoutInMilliseconds: Int64? = nilOrValue(pigeonVar_list[6])

    return StartBotParams(
      url: url,
      token: token,
      shouldEnableMicrophone: shouldEnableMicrophone,
      shouldEnableCamera: shouldEnableCamera,
      headers: headers,
      connectPath: connectPath,
      timeoutInMilliseconds: timeoutInMilliseconds
    )
  }
  func toList() -> [Any?] {
    return [
      url,
      token,
      shouldEnableMicrophone,
      shouldEnableCamera,
      headers,
      connectPath,
      timeoutInMilliseconds,
    ]
  }
  static func == (lhs: StartBotParams, rhs: StartBotParams) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Events that the client receives on a session
///
/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol PipecatEvent {

}

/// Emitted when there's a change in the connection state.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ConnectionStateEvent: Hashable {
  var state: ConnectionState


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConnectionStateEvent? {
    let state = pigeonVar_list[0] as! ConnectionState

    return ConnectionStateEvent(
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      state
    ]
  }
  static func == (lhs: ConnectionStateEvent, rhs: ConnectionStateEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Emitted when there's a problem connecting or during
/// the call session.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BackendErrorEvent: PipecatEvent {
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BackendErrorEvent? {
    let message = pigeonVar_list[0] as! String

    return BackendErrorEvent(
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      message
    ]
  }
  static func == (lhs: BackendErrorEvent, rhs: BackendErrorEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Real-time transcription of user speech,
/// including both partial and final results.
///
/// Generated class from Pigeon that represents data sent in messages.
struct UserTranscriptionEvent: Hashable {
  var text: String
  var isFinal: Bool
  var timestamp: String
  var userId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UserTranscriptionEvent? {
    let text = pigeonVar_list[0] as! String
    let isFinal = pigeonVar_list[1] as! Bool
    let timestamp = pigeonVar_list[2] as! String
    let userId = pigeonVar_list[3] as! String

    return UserTranscriptionEvent(
      text: text,
      isFinal: isFinal,
      timestamp: timestamp,
      userId: userId
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      isFinal,
      timestamp,
      userId,
    ]
  }
  static func == (lhs: UserTranscriptionEvent, rhs: UserTranscriptionEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// The best-effort representation of the bot’s output text, including both
/// spoken and unspoken text. In addition to transcriptions of spoken text,
/// this message type may also include text that the bot outputs but does
/// not speak (e.g., text sent to the client for display purposes only).
///
/// Along with the text, this event includes a spoken flag to indicate whether
/// the text was spoken by the bot or not and an aggregated_by field to indicate
/// what the text represents (e.g. “sentence”, “word”, “code”, “url”).
///
/// Generated class from Pigeon that represents data sent in messages.
struct BotOutputEvent: Hashable {
  /// The output text from the bot.
  var text: String
  /// Indicates if this text was spoken by the bot.
  var isSpoken: Bool
  /// Indicates how the text was aggregated
  /// (e.g., “sentence”, “word”, “code”, “url”).
  ///
  /// “sentence” and “word” are reserved aggregation types defined
  /// by the RTVI standard. Other aggregation types may be defined
  /// by custom text aggregators used by the server.
  var aggregatedBy: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BotOutputEvent? {
    let text = pigeonVar_list[0] as! String
    let isSpoken = pigeonVar_list[1] as! Bool
    let aggregatedBy = pigeonVar_list[2] as! String

    return BotOutputEvent(
      text: text,
      isSpoken: isSpoken,
      aggregatedBy: aggregatedBy
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      isSpoken,
      aggregatedBy,
    ]
  }
  static func == (lhs: BotOutputEvent, rhs: BotOutputEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SpeakingEvent: Hashable {
  var state: SpeakingState


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SpeakingEvent? {
    let state = pigeonVar_list[0] as! SpeakingState

    return SpeakingEvent(
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      state
    ]
  }
  static func == (lhs: SpeakingEvent, rhs: SpeakingEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ServerInsightEvent: PipecatEvent {
  var type: InsightType


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ServerInsightEvent? {
    let type = pigeonVar_list[0] as! InsightType

    return ServerInsightEvent(
      type: type
    )
  }
  func toList() -> [Any?] {
    return [
      type
    ]
  }
  static func == (lhs: ServerInsightEvent, rhs: ServerInsightEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Aggregated user input text that is sent to the LLM.
///
/// Generated class from Pigeon that represents data sent in messages.
struct UserLLMText: PipecatEvent {
  var text: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UserLLMText? {
    let text = pigeonVar_list[0] as! String

    return UserLLMText(
      text: text
    )
  }
  func toList() -> [Any?] {
    return [
      text
    ]
  }
  static func == (lhs: UserLLMText, rhs: UserLLMText) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Individual tokens streamed from the LLM as they are generated.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BotLLMText: PipecatEvent {
  var text: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BotLLMText? {
    let text = pigeonVar_list[0] as! String

    return BotLLMText(
      text: text
    )
  }
  func toList() -> [Any?] {
    return [
      text
    ]
  }
  static func == (lhs: BotLLMText, rhs: BotLLMText) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Audio level data for visualizers
/// Sent at high frequency (~50-100ms intervals)
///
/// Generated class from Pigeon that represents data sent in messages.
struct AudioLevel: Hashable {
  /// Normalized audio level from 0.0 (silent) to 1.0 (loud)
  var level: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AudioLevel? {
    let level = pigeonVar_list[0] as! Double

    return AudioLevel(
      level: level
    )
  }
  func toList() -> [Any?] {
    return [
      level
    ]
  }
  static func == (lhs: AudioLevel, rhs: AudioLevel) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// The per-token text output of the text-to-speech (TTS) service
/// (what the TTS actually says).
///
/// Generated class from Pigeon that represents data sent in messages.
struct BotTTSText: PipecatEvent {
  var text: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BotTTSText? {
    let text = pigeonVar_list[0] as! String

    return BotTTSText(
      text: text
    )
  }
  func toList() -> [Any?] {
    return [
      text
    ]
  }
  static func == (lhs: BotTTSText, rhs: BotTTSText) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct InputStatusUpdatedEvent: Hashable {
  var isCurrentMicrophoneEnabled: Bool
  var isCurrentCameraEnabled: Bool
  var isBotAudioMuted: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InputStatusUpdatedEvent? {
    let isCurrentMicrophoneEnabled = pigeonVar_list[0] as! Bool
    let isCurrentCameraEnabled = pigeonVar_list[1] as! Bool
    let isBotAudioMuted = pigeonVar_list[2] as! Bool

    return InputStatusUpdatedEvent(
      isCurrentMicrophoneEnabled: isCurrentMicrophoneEnabled,
      isCurrentCameraEnabled: isCurrentCameraEnabled,
      isBotAudioMuted: isBotAudioMuted
    )
  }
  func toList() -> [Any?] {
    return [
      isCurrentMicrophoneEnabled,
      isCurrentCameraEnabled,
      isBotAudioMuted,
    ]
  }
  static func == (lhs: InputStatusUpdatedEvent, rhs: InputStatusUpdatedEvent) -> Bool {
    return deepEqualsPipecatApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPipecatApi(value: toList(), hasher: &hasher)
  }
}

private class PipecatApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ConnectionState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SpeakingState(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return InsightType(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return StartBotParams.fromList(self.readValue() as! [Any?])
    case 133:
      return ConnectionStateEvent.fromList(self.readValue() as! [Any?])
    case 134:
      return BackendErrorEvent.fromList(self.readValue() as! [Any?])
    case 135:
      return UserTranscriptionEvent.fromList(self.readValue() as! [Any?])
    case 136:
      return BotOutputEvent.fromList(self.readValue() as! [Any?])
    case 137:
      return SpeakingEvent.fromList(self.readValue() as! [Any?])
    case 138:
      return ServerInsightEvent.fromList(self.readValue() as! [Any?])
    case 139:
      return UserLLMText.fromList(self.readValue() as! [Any?])
    case 140:
      return BotLLMText.fromList(self.readValue() as! [Any?])
    case 141:
      return AudioLevel.fromList(self.readValue() as! [Any?])
    case 142:
      return BotTTSText.fromList(self.readValue() as! [Any?])
    case 143:
      return InputStatusUpdatedEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PipecatApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ConnectionState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? SpeakingState {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? InsightType {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? StartBotParams {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ConnectionStateEvent {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? BackendErrorEvent {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? UserTranscriptionEvent {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? BotOutputEvent {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? SpeakingEvent {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? ServerInsightEvent {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? UserLLMText {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? BotLLMText {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? AudioLevel {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? BotTTSText {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? InputStatusUpdatedEvent {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PipecatApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PipecatApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PipecatApiPigeonCodecWriter(data: data)
  }
}

class PipecatApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PipecatApiPigeonCodec(readerWriter: PipecatApiPigeonCodecReaderWriter())
}

@inline(__always)
private func pipecatApiPigeonMethodCodec() -> FlutterStandardMethodCodec {
  FlutterStandardMethodCodec(readerWriter: PipecatApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PipecatHostApi {
  /// Starts the session and connects to your transport
  func startAndConnect(parameters: StartBotParams, completion: @escaping (Result<Void, Error>) -> Void)
  /// Acts as a dispose too
  func disconnect(completion: @escaping (Result<Void, Error>) -> Void)
  /// Toggle your microphone
  func toggleMicrophone(isEnabled: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  /// Toggle your camera
  func toggleCamera(isEnabled: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  func muteBotAudio(isMuted: Bool, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PipecatHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PipecatApiPigeonCodec.shared }
  /// Sets up an instance of `PipecatHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PipecatHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Starts the session and connects to your transport
    let startAndConnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.startAndConnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startAndConnectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let parametersArg = args[0] as! StartBotParams
        api.startAndConnect(parameters: parametersArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startAndConnectChannel.setMessageHandler(nil)
    }
    /// Acts as a dispose too
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { _, reply in
        api.disconnect { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    /// Toggle your microphone
    let toggleMicrophoneChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.toggleMicrophone\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      toggleMicrophoneChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isEnabledArg = args[0] as! Bool
        api.toggleMicrophone(isEnabled: isEnabledArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      toggleMicrophoneChannel.setMessageHandler(nil)
    }
    /// Toggle your camera
    let toggleCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.toggleCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      toggleCameraChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isEnabledArg = args[0] as! Bool
        api.toggleCamera(isEnabled: isEnabledArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      toggleCameraChannel.setMessageHandler(nil)
    }
    let muteBotAudioChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.muteBotAudio\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      muteBotAudioChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isMutedArg = args[0] as! Bool
        api.muteBotAudio(isMuted: isMutedArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      muteBotAudioChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class EventsStreamHandler: PigeonEventChannelWrapper<PipecatEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: EventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatEventStreamApi.events"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<PipecatEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: pipecatApiPigeonMethodCodec())
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class LocalAudioLevelStreamHandler: PigeonEventChannelWrapper<AudioLevel> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: LocalAudioLevelStreamHandler) {
    var channelName = "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatEventStreamApi.localAudioLevel"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<AudioLevel>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: pipecatApiPigeonMethodCodec())
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class RemoteAudioLevelStreamHandler: PigeonEventChannelWrapper<AudioLevel> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: RemoteAudioLevelStreamHandler) {
    var channelName = "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatEventStreamApi.remoteAudioLevel"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<AudioLevel>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: pipecatApiPigeonMethodCodec())
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class BotOutputStreamHandler: PigeonEventChannelWrapper<BotOutputEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: BotOutputStreamHandler) {
    var channelName = "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatEventStreamApi.botOutput"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<BotOutputEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: pipecatApiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class UserTranscriptionsStreamHandler: PigeonEventChannelWrapper<UserTranscriptionEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: UserTranscriptionsStreamHandler) {
    var channelName = "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatEventStreamApi.userTranscriptions"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<UserTranscriptionEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: pipecatApiPigeonMethodCodec())
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class SpeakingEventsStreamHandler: PigeonEventChannelWrapper<SpeakingEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: SpeakingEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatEventStreamApi.speakingEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<SpeakingEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: pipecatApiPigeonMethodCodec())
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class ConnectionStateEventsStreamHandler: PigeonEventChannelWrapper<ConnectionStateEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: ConnectionStateEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatEventStreamApi.connectionStateEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<ConnectionStateEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: pipecatApiPigeonMethodCodec())
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class InputStatusEventsStreamHandler: PigeonEventChannelWrapper<InputStatusUpdatedEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: InputStatusEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatEventStreamApi.inputStatusEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<InputStatusUpdatedEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: pipecatApiPigeonMethodCodec())
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
