// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.kcniverba.pipecat_flutter_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PipecatApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class ConnectionState(val raw: Int) {
  CONNECTING(0),
  CONNECTED(1),
  DISCONNECTED(2);

  companion object {
    fun ofRaw(raw: Int): ConnectionState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class SpeakingState(val raw: Int) {
  /** Emitted when the user begins speaking */
  USER_STARTED_SPEAKING(0),
  /** Emitted when the user stops speaking */
  USER_STOPPED_SPEAKING(1),
  /** Emitted when the bot begins speaking */
  BOT_STARTED_SPEAKING(2),
  /** Emitted when the bot stops speaking */
  BOT_STOPPED_SPEAKING(3);

  companion object {
    fun ofRaw(raw: Int): SpeakingState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class InsightType(val raw: Int) {
  BOT_LLM_STARTED(0),
  BOT_LLM_STOPPED(1),
  BOT_TTS_STARTED(2),
  BOT_TTS_STOPPED(3);

  companion object {
    fun ofRaw(raw: Int): InsightType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Parameters for starting the bot and connecting
 *
 * Used to connect to your transport (for example: a Daily room)
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StartBotParams (
  /** API endpoint to connect to */
  val url: String,
  /**
   * Optional auth token
   *
   * The package does not prepend "Bearer " to your token, ensure that
   * it has the proper value first before adding it.
   */
  val token: String? = null,
  /** Should enable microphone when starting a call */
  val shouldEnableMicrophone: Boolean,
  /** Should enable camera when starting a call */
  val shouldEnableCamera: Boolean,
  /** Additional headers */
  val headers: Map<String, String>? = null,
  /** Defaults to `/connect` */
  val connectPath: String,
  /** Defaults to 30000 natively */
  val timeoutInMilliseconds: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StartBotParams {
      val url = pigeonVar_list[0] as String
      val token = pigeonVar_list[1] as String?
      val shouldEnableMicrophone = pigeonVar_list[2] as Boolean
      val shouldEnableCamera = pigeonVar_list[3] as Boolean
      val headers = pigeonVar_list[4] as Map<String, String>?
      val connectPath = pigeonVar_list[5] as String
      val timeoutInMilliseconds = pigeonVar_list[6] as Long?
      return StartBotParams(url, token, shouldEnableMicrophone, shouldEnableCamera, headers, connectPath, timeoutInMilliseconds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      token,
      shouldEnableMicrophone,
      shouldEnableCamera,
      headers,
      connectPath,
      timeoutInMilliseconds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is StartBotParams) {
      return false
    }
    if (this === other) {
      return true
    }
    return PipecatApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Events that the client receives on a session
 *
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class PipecatEvent 
/**
 * Emitted when there's a change in the connection state.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ConnectionStateEvent (
  val state: ConnectionState
) : PipecatEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConnectionStateEvent {
      val state = pigeonVar_list[0] as ConnectionState
      return ConnectionStateEvent(state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ConnectionStateEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return PipecatApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Emitted when there's a problem connecting or during
 * the call session.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BackendErrorEvent (
  val message: String
) : PipecatEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BackendErrorEvent {
      val message = pigeonVar_list[0] as String
      return BackendErrorEvent(message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BackendErrorEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return PipecatApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Real-time transcription of user speech,
 * including both partial and final results.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class UserTranscriptionEvent (
  val text: String,
  val isFinal: Boolean,
  val timestamp: String,
  val userId: String
) : PipecatEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UserTranscriptionEvent {
      val text = pigeonVar_list[0] as String
      val isFinal = pigeonVar_list[1] as Boolean
      val timestamp = pigeonVar_list[2] as String
      val userId = pigeonVar_list[3] as String
      return UserTranscriptionEvent(text, isFinal, timestamp, userId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
      isFinal,
      timestamp,
      userId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is UserTranscriptionEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return PipecatApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * The best-effort representation of the bot’s output text, including both
 * spoken and unspoken text. In addition to transcriptions of spoken text,
 * this message type may also include text that the bot outputs but does
 * not speak (e.g., text sent to the client for display purposes only).
 *
 * Along with the text, this event includes a spoken flag to indicate whether
 * the text was spoken by the bot or not and an aggregated_by field to indicate
 * what the text represents (e.g. “sentence”, “word”, “code”, “url”).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BotOutputEvent (
  /** The output text from the bot. */
  val text: String,
  /** Indicates if this text was spoken by the bot. */
  val isSpoken: String,
  /**
   * Indicates how the text was aggregated
   * (e.g., “sentence”, “word”, “code”, “url”).
   *
   * “sentence” and “word” are reserved aggregation types defined
   * by the RTVI standard. Other aggregation types may be defined
   * by custom text aggregators used by the server.
   */
  val aggregatedBy: String
) : PipecatEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BotOutputEvent {
      val text = pigeonVar_list[0] as String
      val isSpoken = pigeonVar_list[1] as String
      val aggregatedBy = pigeonVar_list[2] as String
      return BotOutputEvent(text, isSpoken, aggregatedBy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
      isSpoken,
      aggregatedBy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BotOutputEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return PipecatApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SpeakingEvent (
  val state: SpeakingState
) : PipecatEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SpeakingEvent {
      val state = pigeonVar_list[0] as SpeakingState
      return SpeakingEvent(state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SpeakingEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return PipecatApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ServerInsightEvent (
  val type: InsightType
) : PipecatEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ServerInsightEvent {
      val type = pigeonVar_list[0] as InsightType
      return ServerInsightEvent(type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ServerInsightEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return PipecatApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Aggregated user input text that is sent to the LLM.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class UserLLMText (
  val text: String
) : PipecatEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UserLLMText {
      val text = pigeonVar_list[0] as String
      return UserLLMText(text)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is UserLLMText) {
      return false
    }
    if (this === other) {
      return true
    }
    return PipecatApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Individual tokens streamed from the LLM as they are generated.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BotLLMText (
  val text: String
) : PipecatEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BotLLMText {
      val text = pigeonVar_list[0] as String
      return BotLLMText(text)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BotLLMText) {
      return false
    }
    if (this === other) {
      return true
    }
    return PipecatApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Audio level data for visualizers
 * Sent at high frequency (~50-100ms intervals)
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AudioLevel (
  /** Normalized audio level from 0.0 (silent) to 1.0 (loud) */
  val level: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AudioLevel {
      val level = pigeonVar_list[0] as Double
      return AudioLevel(level)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      level,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AudioLevel) {
      return false
    }
    if (this === other) {
      return true
    }
    return PipecatApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * The per-token text output of the text-to-speech (TTS) service
 * (what the TTS actually says).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BotTTSText (
  val text: String
) : PipecatEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BotTTSText {
      val text = pigeonVar_list[0] as String
      return BotTTSText(text)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BotTTSText) {
      return false
    }
    if (this === other) {
      return true
    }
    return PipecatApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PipecatApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ConnectionState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SpeakingState.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          InsightType.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StartBotParams.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConnectionStateEvent.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BackendErrorEvent.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UserTranscriptionEvent.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BotOutputEvent.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SpeakingEvent.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ServerInsightEvent.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UserLLMText.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BotLLMText.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AudioLevel.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BotTTSText.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ConnectionState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is SpeakingState -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is InsightType -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is StartBotParams -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ConnectionStateEvent -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is BackendErrorEvent -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is UserTranscriptionEvent -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is BotOutputEvent -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is SpeakingEvent -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is ServerInsightEvent -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is UserLLMText -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is BotLLMText -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is AudioLevel -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is BotTTSText -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val PipecatApiPigeonMethodCodec = StandardMethodCodec(PipecatApiPigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PipecatHostApi {
  /** Starts the session and connects to your transport */
  fun startAndConnect(parameters: StartBotParams, callback: (Result<Unit>) -> Unit)
  /** Acts as a dispose too */
  fun disconnect(callback: (Result<Unit>) -> Unit)
  /** Toggle your microphone */
  fun toggleMicrophone(isEnabled: Boolean, callback: (Result<Unit>) -> Unit)
  /** Toggle your camera */
  fun toggleCamera(isEnabled: Boolean, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by PipecatHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PipecatApiPigeonCodec()
    }
    /** Sets up an instance of `PipecatHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PipecatHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.startAndConnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val parametersArg = args[0] as StartBotParams
            api.startAndConnect(parametersArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PipecatApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PipecatApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.disconnect{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PipecatApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PipecatApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.toggleMicrophone$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val isEnabledArg = args[0] as Boolean
            api.toggleMicrophone(isEnabledArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PipecatApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PipecatApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatHostApi.toggleCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val isEnabledArg = args[0] as Boolean
            api.toggleCamera(isEnabledArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PipecatApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PipecatApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class PipecatApiPigeonStreamHandler<T>(
    val wrapper: PipecatApiPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface PipecatApiPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class EventsStreamHandler : PipecatApiPigeonEventChannelWrapper<PipecatEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: EventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatEventStreamApi.events"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = PipecatApiPigeonStreamHandler<PipecatEvent>(streamHandler)
      EventChannel(messenger, channelName, PipecatApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from PipecatApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<PipecatEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class LocalAudioLevelStreamHandler : PipecatApiPigeonEventChannelWrapper<AudioLevel> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: LocalAudioLevelStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatEventStreamApi.localAudioLevel"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = PipecatApiPigeonStreamHandler<AudioLevel>(streamHandler)
      EventChannel(messenger, channelName, PipecatApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from PipecatApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<AudioLevel>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class RemoteAudioLevelStreamHandler : PipecatApiPigeonEventChannelWrapper<AudioLevel> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: RemoteAudioLevelStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.com.kcniverba.pipecat_flutter.PipecatEventStreamApi.remoteAudioLevel"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = PipecatApiPigeonStreamHandler<AudioLevel>(streamHandler)
      EventChannel(messenger, channelName, PipecatApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from PipecatApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<AudioLevel>) {}

override fun onCancel(p0: Any?) {}
}
      
